config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "top#first_view"

  resources :posts do
    resources :comments, only: %i[create], shallow: true
    collection do
      get :greats
    end
  end
  resources :greats, only: %i[create destroy]

  get '/privacy_policy', to: 'top#privacy_policy'  
end

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="font-yomogi alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="font-yomogi bg-lime-300 body-font shadow relative">
   <div class="md:ml-auto flex flex-wrap text-base justify-center  text-pink-500">
    <%= link_to "プライバシーポリシー", privacy_policy_path ,class: "mr-5 hover:text-yellow-700" %>
    <%= link_to "利用規約", "" ,class: "mr-5 hover:text-yellow-700" %>
    <%= link_to "お問い合せ", "https://forms.gle/w5212uawEo3YTEWk9" ,class: "mr-5 hover:text-yellow-700", target: :_blank, rel: "noopener noreferrer" %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="bg-lime-300 font-yomogi shadow">
  <div class="container mx-auto flex flex-wrap flex-col md:flex-row items-center">
    <%= link_to image_tag('logo_type.jpg', size: '150x150'), root_path%>
    <div class="font-yomogi md:ml-auto flex flex-wrap items-center text-base md:text-xl justify-center text-pink-500">
      <%# マイページ %>
      <% if user_signed_in? %>
        <%#= link_to t('shared.header.my_page'), "" ,class: "mr-5 hover:text-yellow-700" %>
      <% end %>
      <%# 一覧画面 %>
      <%= link_to t('shared.header.look'), posts_path , class: "mr-5 hover:text-yellow-700"%>
      <%# 新規投稿 %>
        <%= link_to t('shared.header.posting'), new_post_path , class: "mr-5 hover:text-yellow-700"%>
      <%# ログインしてるかどうかのif文 %>
      <% if user_signed_in? %>
        <%= button_to destroy_user_session_path , method: :delete, alert: "本当にログアウトしますか？", class: "hover:text-yellow-700" do %>
          ログアウト
        <% end %>
      <% else %>
        <%= link_to new_user_session_path , class: "hover:text-yellow-700" do %>
          ログイン
        <% end %>
      <% end %>
    </div>
  </div>
</header>