config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "top#first_view"

  resources :posts do
    resources :comments, only: %i[create], shallow: true
    collection do
      get :greats
    end
  end
  resources :greats, only: %i[create destroy]

  get '/privacy_policy', to: 'top#privacy_policy'  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :post_image
  #dependent: :destroy = 親モデルを削除する際に、その親モデルに紐づく「子モデル」も一緒に削除できる
  has_many :comments, dependent: :destroy
  has_many :greats, dependent: :destroy

  mount_uploader :post_image, PostImageUploader

  validates :name, presence: true, length: { maximum: 31 }
  validates :body, presence: true, length: { maximum: 31 }

  def greats_by?(user)
    greats.where(user_id: user).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :destroy, :edit, :update, :destroy]
  #AWS Rekognition
  require 'aws-sdk-rekognition'

  def index
    @posts = Post.all.includes([:user, :greats]).order(created_at: :desc).page(params[:page]).per(12)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    rekognition_client = Aws::Rekognition::Client.new(region: 'ap-northeast-1', access_key_id: ENV['AWS_ACCESS_KEY_ID'], secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'])

    if @post.save
      image = @post.post_image
      if image.present?
        # 画像に対してRekognitionを実行し、ラベル情報を取得する
        response = rekognition_client.detect_labels(
          image: {
            s3_object: {
              bucket: ENV['AWS_S3_BUCKET_NAME'],
              name: image.path
            }
          },
          max_labels: 5
        )
        
        #binding.pry

        # Rekognitionの結果に基づいて、投稿の可否を判断する
        #binding.pry
        if response.labels.any? { |label| label.name.downcase.include?('person') }
          @post.destroy
          flash[:alert] = '投稿が失敗しました。人間が写っています。'
          render :new
        elsif ['animal', 'cat', 'dog', 'pet'].any? { |word| response.labels.any? { |label| label.name.downcase.include?(word) } }
          redirect_to post_path(@post)
          flash[:alert] = 'もふもふの投稿が成功しました！'
        else
          @post.destroy
          render :new
          flash[:alert] = 'ﾓﾌｼﾞｬﾅｲ・・・'
        end
      else
        flash[:alert] = '投稿が失敗しました。画像を選択してください。'
        render :new
      end
    else
      render :new
      flash[:alert] = '投稿が失敗しました。タイトルと本文、写真は必須です。'
    end
  end
  
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc)
  end

  def greats
    @great_posts = current_user.great_posts.includes(:user).order(created_at: :desc)
  end 

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      flash[:success] = t('defaults.message.updated', item: @post.name)
      redirect_to @post
    else
      flash.now[:danger] = t('defaults.message.not_updated', item: @post.name)
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to posts_path
    flash[:success] = t('defaults.message.deleted', item: @post.name)
  end

  private

  def post_params
    params.require(:post).permit(:name, :body, :post_image, :post_image_cache)
  end

  def rekognition_tags(image, s3)
    # Rekognitionのクライアントを作成
    rekognition_client = Aws::Rekognition::Client.new(region: 'ap-northeast-1', access_key_id: ENV['AWS_ACCESS_KEY_ID'], secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'])
    
    # 画像をS3にアップロード
    obj = s3.bucket(ENV['AWS_S3_BUCKET_NAME']).object(image.filename)
    obj.upload_file(image.tempfile, acl: 'public-read')

    # 画像に対してRekognitionを実行し、ラベル情報を取得する
    response = rekognition_client.detect_labels(
      image: {
        s3_object: {
          bucket: ENV['AWS_S3_BUCKET_NAME'],
          name: image.filename
        }
      },
      max_labels: 5
    )

    # ラベル情報からタグ名の配列を作成して返す
    response.labels.map(&:name)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_crud_menus.html.erb
<div class="float-right flex flex-row">
  <%= button_to post_path(post), id: "button-delete-#{post.id}", method: :delete, data: { turbo_method: :delete, turbo_confirm: t('defaults.message.delete_confirm') } do %>
    <i class="fa-regular fa-trash-can fa-2xl text-gray-500"></i>
  <% end %>
  <%= button_to edit_post_path(post.id), id: "button-edit-#{post.id}", method: :get do %>
    <i class="fa-regular fa-pen-to-square fa-2xl text-gray-500 ml-4"></i>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f| %>
  <div class="text-red-900">
              <!-- にくきゅう右　-->
    <div class="absolute right-20">
      <%= image_tag 'nikukyu.jpg', size: "50x50" %>
    </div>
    <div class="absolute right-10 mt-5">
      <%= image_tag 'nikukyu.jpg', size: "50x50" %>
    </div>
    <!-- 投稿名 -->
    <div class="flex items-center justify-center text-center relative mt-3">
      <div class="form-group items-center">
        <%= f.label t('posts.new.name') %>
        <%= f.text_field :name, class: 'form-control', placeholder: 'もふのなまえ' %>
      </div>
    </div>
        <!-- にくきゅう左　-->
    <div class="absolute left-0">
      <%= image_tag 'nikukyu.jpg', size: "50x50" %>
    </div>
    <div class="absolute left-10 mt-5">
      <%= image_tag 'nikukyu.jpg', size: "50x50" %>
    </div>
    <!-- 投稿本文 -->
    <div class="flex items-center justify-center text-center">
      <div class="form-group relative mt-3">
        <%= f.label t('posts.new.body') %>
        <div class="container">
          <%= f.text_area :body, class: 'form-control  lg:w-80', rows: 3, placeholder: 'おすすめポイント🐾31文字で！' %>
        </div>
      </div>

      <!-- にくきゅう右左　-->
      <div class="absolute left-0">
        <%= image_tag 'nikukyu.jpg', size: "50x50" %>
      </div>
      <div class="absolute right-10 mt-5">
        <%= image_tag 'nikukyu.jpg', size: "50x50" %>
      </div>
    </div>
                  <!-- にくきゅう右　-->
    <div class="absolute right-20 lg:flex lg:justify-center lg:items-center">
      <%= image_tag 'nikukyu.jpg', size: "50x50" %>
    </div>
    <div class="absolute right-10 mt-5">
      <%= image_tag 'nikukyu.jpg', size: "50x50" %>
    </div>
    <div class="form-group relative">
      <%#= f.label t('posts.new.post_image') %>
      <%= f.file_field :post_image, onchange: 'previewFileWithId(preview)', class: 'form-control mb-3 mt-3' %>
      <%= f.hidden_field :post_image_cache %>
    </div>
    <div class='mt-3 mb-3 relative'>
      <%#= image_tag post.post_image.url, id: 'preview', size: '300x200' %>
    </div>
    <%= f.submit class: 'btn btn-outline btn-success m-3' %>
  </div>
<% end %>

app/views/posts/_great.html.erb
<turbo-frame id="great-button-<%= post.id %>">
  <%= button_to greats_path(post_id: post.id),
                id: "js-great-button-for-post-#{post.id}", 
                method: :post,
                remote: true,
                data: { type: :script } do %>
    <%# ★ %>
    <i class="fa-regular fa-star"></i>
  <% end %>
</turbo-frame>

app/views/posts/_great_button.html.erb
<turbo-frame id="great-button-<%= post.id %>">
  <% if current_user.great?(post) %>
    <%= render 'ungreat', { post: post } %>
  <% else %>
    <%= render 'great', { post: post } %>
  <% end %>
  <div class='mt-1 text-xl'>
        <%= post.greats.count %>
  </div>
</turbo-frame>

app/views/posts/_iine_buttons.html.erb
<div class='mr10 float-right'>
  <%#= great（星） %>
  <div class='text-yellow-400 fa-xl'>
    <%= render 'great_button', post: post %>
  </div>
</div>

app/views/posts/_post.html.erb
<style>
  .img-container {
  width: 360px;
  height: 260px;
}
  .img-container img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
</style>

<%# 投稿の枠組みのテンプレート URL:https://tailblocks.cc/ %>
<section class="text-gray-600 body-font flex items-center justify-center text-center">
  <div id="post-id-<%= post.id %>">
    <div class="container px-5 py-5 mx-auto">
            <!-- にくきゅう右　-->
              <div class="absolute right-5">
                <%= image_tag 'nikukyu.jpg', size: "50x50" %>
              </div>
              <div class="absolute right-0 mt-10">
                <%= image_tag 'nikukyu.jpg', size: "50x50" %>
              </div>
        <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
          <div class="img-container">
            <%= image_tag post.post_image_url, class: 'card-img-top' %>
          </div>
          <div class="font-yomogi p-6">
            <h1 class="title-font text-lg font-medium text-green-600 mb-3">
              <font style="vertical-align: inherit;">
                <%= link_to post.name, post_path(post) %>
              </font>
            </h1>
            <p class="leading-relaxed mb-3">
              <font style="vertical-align: inherit;">
                <p class="card-text"><%= post.body %></p>
              </font>
            </p>
            <div class="flex items-center flex-wrap justify-end"">
                <span class="text-gray-400 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm pr-3 py-1 border-r-2 border-gray-200">
                  <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                    <font style="vertical-align: inherit;">
                      <div class="list-inline-item">
                        <!-- Twitterシェア -->
                        <%= link_to "https://twitter.com/share?url=#{ request.url }&text=みてみて🐾%0a%0a「#{ post.name }」は正義🐾%0a%0a&hashtags=もふは正義,もふもふ", target: '_blank', class: 'fa-brands fa-twitter fa-2xl mr-3', style: 'color: #909398;' do %>
                        <% end %>
                        <!-- 削除・編集button -->
                        <% if current_user && current_user.own?(post) %>
                          <%= render 'crud_menus', post: post %>
                        <% elsif current_user %>
                          <%= render 'iine_buttons', post: post %>
                        <% end %>
                      </div>
                    </font>
                  </svg>
                </span>

              <span class="text-gray-400 inline-flex items-center leading-none text-sm">
                <%= link_to post_path(post) do %>
                  <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                    <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                  </svg>
                <% end %>
                <!-- にくきゅう左　-->
                  <div class="absolute left-5">
                    <%= image_tag 'nikukyu.jpg', size: "50x50" %>
                  </div>
                  <div class="absolute left-10 mt-20">
                    <%= image_tag 'nikukyu.jpg', size: "50x50" %>
                  </div>
                <font style="vertical-align: inherit;">
                  <font style="vertical-align: inherit;"><%= post.comments.count %></font>
                </font>
              </span>
            </div>
          </div>
        </div>
    </div>
  </div>
</section>

app/views/posts/_ungreat.html.erb
<turbo-frame id="great-button-<%= post.id %>">
  <%= button_to great_path(current_user.greats.find_by(post_id: post.id)), 
                id: "js-great-button-for-post-#{post.id}", 
                method: :delete,
                remote: true,
                data: { type: :script } do %>
    <%# ☆ %>
    <i class="fa-solid fa-star"></i>
  <% end %>
</turbo-frame>

app/views/posts/edit.html.erb
<div class="font-yomogi text-red-900 container flex items-center justify-center text-center">
  <div class="row">
    <div class="w-full max-w-lg">
      <% content_for(:name, @post.name) %>
        <article class="card">
          <div class="px-6 py-4">
            <h1 class="text-3xl mt-3"><%= t('.title') %></h1>
            <%= render 'form', { post: @post } %>
          </dev>
        </article>
      </dev>
  </dev>
</dev>

app/views/posts/index.html.erb
<div class="font-yomogi text-red-900 font container pt-3">
  <div class="items-center justify-center text-center">
    <div class="row">
      <div class="col-12">
        <div class="row">
          <% if @posts.present? %>
            <div class="flex flex-row flex-wrap">
              <% @posts.each do |post| %>
                <div class="md:w-1/2 lg:w-1/3 p-1">
                  <%= render partial: 'post', locals: { post: post } %>
                </div>
              <% end %>
          <% else %>
            <p><%= t('.no_result') %><%= image_tag 'nikukyu.jpg', size: "50x50" %></p>
          <% end %>
        </div>
        <div class="font-yomogi items-center justify-center text-center my-6 text-xl text-pink-600">
            <%= paginate @posts %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="font-yomogi text-red-900 container flex items-center justify-center text-center">
   <div class="row">
     <div class="col-lg-8 offset-lg-2">
       <h1 class="text-3xl"><%= t '.title' %></h1>
       <%= render 'form', { post: @post } %>
     </div>
   </div>
 </div>

app/views/posts/show.html.erb
<div class="font-yomogi text-red-900 container flex items-center justify-center text-center">
   <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1 class="text-3xl mt-3"><%= t('.title') %></h1>
        <!-- にくきゅう右　-->
          <div class="absolute right-5">
            <%= image_tag 'nikukyu.jpg', size: "50x50" %>
          </div>
          <div class="absolute right-0 mt-10">
            <%= image_tag 'nikukyu.jpg', size: "50x50" %>
          </div>
      <!-- 掲示板内容 -->
      <article class="card">
        <div class="card-body">
          <div class='row'>
            <div class='col-md-3'>
              <%= image_tag @post.post_image.url, class: 'card-img-top img-fluid relative', size: '300x200' %>
            </div>
            <div class='col-md-9 relative'>
              <h3 class="d-inline text-xl"><%= @post.name %></h3>
              <!-- 投稿者以外に見せない -->
              <h6 class="text-lg"><%= simple_format(@post.body) %></h6>
              <!-- 削除・編集button -->
              <% if current_user && current_user.own?(@post) %>
                <%= render 'crud_menus', post: @post %>
              <% end %>
            </div>
          </div>
          <!-- Twitterシェア -->
          <% set_meta_tags  og: { image: image_url(@post.post_image_url) }, twitter: { image: image_url(@post.post_image_url) } %>
          <%# binding.pry %>
          <%= link_to "https://twitter.com/share?url=#{ request.url }&text=みてみて🐾%0a%0a「#{ @post.name }」は正義🐾%0a%0a&hashtags=もふは正義,もふもふ", target: '_blank', class: 'fa-brands fa-twitter fa-2xl relative mt-3', style: 'color: #909398;' do %>
          <% end %>
        </div>
          <!-- にくきゅう左　-->
            <div class="absolute left-5">
              <%= image_tag 'nikukyu.jpg', size: "50x50" %>
            </div>
            <div class="absolute left-10 mt-20">
              <%= image_tag 'nikukyu.jpg', size: "50x50" %>
            </div>
        <% if current_user %>
          <!-- コメントフォーム -->
            <%= render 'comments/form', { post: @post, comment: @comment } %>
        <% end %>
          <!-- コメントエリア -->
            <%= render 'comments/comments', { comments: @comments } %>
      </article>
    </div>
  </div>
</div>